//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCareV2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ChiTietPhuTungLuanChuyenEntities : DbContext
    {
        public ChiTietPhuTungLuanChuyenEntities()
            : base("name=ChiTietPhuTungLuanChuyenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<LayChiTietPhuTungTheoDonDat_Result> LayChiTietPhuTungTheoDonDat(Nullable<int> idXuatKho, Nullable<int> idCongTy)
        {
            var idXuatKhoParameter = idXuatKho.HasValue ?
                new ObjectParameter("IdXuatKho", idXuatKho) :
                new ObjectParameter("IdXuatKho", typeof(int));
    
            var idCongTyParameter = idCongTy.HasValue ?
                new ObjectParameter("IdCongTy", idCongTy) :
                new ObjectParameter("IdCongTy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayChiTietPhuTungTheoDonDat_Result>("LayChiTietPhuTungTheoDonDat", idXuatKhoParameter, idCongTyParameter);
        }
    }
}
